### PR TITLE
Making functional without cv2

### PR DESCRIPTION
**Pull request by mabirck**
OpenCV is painful to handle, sometimes is not in hand on new installations.

### CODE REVIEW

**Comment by dgriff777** [comment]
@mabirck 
I agree it can be annoying but I saw the least image distortion resizing with cv2 when I compared to others so I think best to leave as is

**Comment by dgriff777** [comment]
added resize options if you don't want to use cv2. just have to uncomment the import line for preference
```
from cv2 import resize
#from skimage.transform import resize
#from scipy.misc import imresize as resize
```

**Comment by mabirck** [comment]
I understand, thanks for the answer, congrats for the project, it is nicely implemented. You rock!

**Comment by dgriff777** [comment]
Thanks! Had fun with it. It's a great algorithm which I really thought had great potential and goal of project was I wanted to see what it's real performance limits were if implemented in what I thought most optimal way. And have been very impressed!

**Comment by mabirck** [comment]
Nice, I was impressed when I found your results, since replication is very hard due to hidden hyper parameter an so on... I tracked down a3c versions on github since I need the code for researches purposes and Universe Starter Agent from openAI which is a good start, the code is very messy to make modifications!!

**Comment by dgriff777** [comment]
The universe starter agent is good but it's very very optimized for Pong though and doesn't have same performance on other games

**Comment by dgriff777** [comment]
yeah model is a little different than a3c paper in some ways but same general idea. For games trained have been able to surpass on the results in a3c paper. The gym v-0 environments are much harder than the ones used in paper and have short timestep limits that limit the performance as well makes actions repeatedly randomly with probability 0.25. They have the hyper parameters from author of a3c here https://github.com/muupan/async-rl/wiki if your looking for it.

**Pull request closed without merging**
